In [ ]:
print("hello")

hello


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
print(torch.__version__)

2.6.0+cu124


**Introduction to tensors**
 1. creating tensors

     pytorch tensors are created using torch.tensor

In [ ]:
#scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [ ]:
#dimension in a scalar tensor
scalar.ndim

0

In [ ]:
#get tensor back as python int
scalar.item()

7

In [ ]:
#vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
#dimension in vector tensor
vector.ndim

1

In [ ]:
#it has 2 elements in 1 dimension.
vector.shape

torch.Size([2])

In [ ]:
#MATRIX
MATRIX=torch.tensor([[7,8],
                   [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
#TENSOR
TENSOR=torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
#we have 1 3x3 TENSOR
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
TENSOR[0][2]

tensor([7, 8, 9])

In [ ]:
TENSOR[0][1][2]

tensor(6)

In [ ]:
TENSOR1=torch.tensor([[[1]]])
print(TENSOR1)
print(TENSOR1.ndim)
print(TENSOR1.shape)

tensor([[[1]]])
3
torch.Size([1, 1, 1])


In [ ]:
TENSOR2 = torch.tensor([
    [ [1, 2, 3],
      [1, 2, 4],
      [4, 4, 5] ],

    [ [3, 2, 1],
      [4, 3, 2],
      [5, 5, 5] ],

    [ [4, 2, 5],
      [2, 4, 3],
      [2, 4, 5] ]
])
print(TENSOR2)
print(TENSOR2.ndim)
print(TENSOR2.shape)

tensor([[[1, 2, 3],
         [1, 2, 4],
         [4, 4, 5]],

        [[3, 2, 1],
         [4, 3, 2],
         [5, 5, 5]],

        [[4, 2, 5],
         [2, 4, 3],
         [2, 4, 5]]])
3
torch.Size([3, 3, 3])


In [ ]:
TENSOR2[2][2][1]

tensor(4)

**Random tensors**

Random tensors are important because the way many neural networks learn is that they start with tensors full of rndom numbers and then adjust those random numbers to better represent the data.

start with random number->look at data->update random number->look at data->uodate random numbers...

In [ ]:
#create a random tensor of size(3,4)
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.8557, 0.6773, 0.2824, 0.3601],
        [0.5710, 0.8815, 0.2038, 0.5136],
        [0.7455, 0.6079, 0.0398, 0.8270]])

In [ ]:
random_tensor.ndim

2

In [ ]:
#crete a random tensor with similar shape to an image tensor,size parameter is implicit
random_image_size_tensor=torch.rand(size=(224,224,3))     #height,width,channels
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

zeros and ones

In [ ]:
#create a tensor of all zeros
zeros=torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#create a tensor of all ones
ones=torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

create a range of tensors and tensors-like


In [ ]:
torch.range(0,10)

<ipython-input-29-497691777>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.arange(start=-1,end=1000,step=77)

tensor([ -1,  76, 153, 230, 307, 384, 461, 538, 615, 692, 769, 846, 923])

In [ ]:
one_to_ten=torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#creating tensors like, same shape like a tensor you want to be  but value 0
ten_zeros=torch.zeros_like(input=one_to_ten)
print(ten_zeros)
ten_zeros.ndim

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


1

Tensor datatypes


In [ ]:
#float 32 tensor
float_32_tensor=torch.tensor([3.0,6.0,9.0],dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype  # default datatype of a tensor is float 32 even if we mention dtype as none

torch.float32

In [ ]:
#int tensor
int_tensor=torch.tensor([3.0,6.0,9.2],dtype=torch.int)
int_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
#float 16 tensor
float_16_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=torch.float16,  #what datatype is the tensor
                             device=None,           #cou,gou,etc, what device your tensor is on?
                             requires_grad=False)   #hether or not to track gradients

In [ ]:
floar_16_tensor=float_32_tensor.type(torch.float16)   #conversion
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor=torch.tensor([3,6,9], dtype=torch.int32)

In [ ]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

Getting information from tensor

tensor attributes


In [ ]:
#to get data type from a tensor
some_tensor=torch.rand(3,4)
some_tensor
print(f"datatype of tensor: {some_tensor.dtype}")

datatype of tensor: torch.float32


In [ ]:
#to get shape from a tensor
print(f"shape of tensor is: {some_tensor.shape}")

shape of tensor is: torch.Size([3, 4])


In [ ]:
#to get device on which tensor is running
print(f"device of tensor is:{some_tensor.device}")

device of tensor is:cpu


**manipulating tensors**
(tensor operations include:)

1.Addition

2.subtraction

3.multiplication(element-wise)

4.division

5.matrix multiplication

In [ ]:
#element wise addition
tensor=torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [ ]:
#elemnt wise multiplication
tensor*10

tensor([10, 20, 30])

In [ ]:
#subtraction
tensor-10

tensor([-9, -8, -7])

In [ ]:
#pytorch in-built functions
torch.mul(tensor,10)
torch.add(tensor,10)
torch.sub(tensor,10)

tensor([-9, -8, -7])

In [ ]:
#matrix multiplication (dot product)
print(tensor,"*",tensor)
print(f"equals: {tensor*tensor}")   # * gives element wise multiplication
torch.matmul(tensor,tensor)


tensor([1, 2, 3]) * tensor([1, 2, 3])
equals: tensor([1, 4, 9])


tensor(14)

In [ ]:
#matrix multiplication by hand
value=0
for i in range (len(tensor)):
  value+=tensor[i] * tensor[i]
print(value)

tensor(14)


In [ ]:
torch.matmul(torch.rand(3,2),torch.rand(3,2))   #very common error since the inner dimension does not match, which is necessary for matrix multiplication

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
#shape errors=3x2 and 3x2
#how to fix this? use transpose
tensor_A= torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B=torch.tensor([[7,10],
                       [8,11],
                       [9,12]])
torch.mm(tensor_A,tensor_B)    #mm is equal to matmul

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A= torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B=torch.tensor([[7,10],
                       [8,11],
                       [9,12]])
print(tensor_A.shape,tensor_B.shape)
tensor_B.T
print(torch.matmul(tensor_A,tensor_B.T))

torch.Size([3, 2]) torch.Size([3, 2])
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [ ]:
print(f"tensor_A shape: {tensor_A.shape}")
print(f"tensor_B shape: {tensor_B.shape}")
print(f"tensor_B.T shape: {tensor_B.T.shape}")
print(f"torch.matmul(tensor_A,tensor_B.T) shape: {torch.matmul(tensor_A,tensor_B.T).shape}")
print(tensor_A @ tensor_B.T)

tensor_A shape: torch.Size([3, 2])
tensor_B shape: torch.Size([3, 2])
tensor_B.T shape: torch.Size([2, 3])
torch.matmul(tensor_A,tensor_B.T) shape: torch.Size([3, 3])
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


**Tensor aggregation of certain Tensor values**

min,max,sum,etc


In [ ]:
x=torch.arange(start=0,end=100,step=10)
print(x)
print(torch.min(x),x.min())

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
tensor(0) tensor(0)


In [ ]:
print(torch.max(x),x.max())

tensor(90) tensor(90)


In [ ]:
torch.mean(x.type(torch.float32))       #mean can only operate on float32(default) datatype
x.type(torch.float32).mean()

tensor(45.)

In [ ]:
torch.sum(x)
x.sum()

tensor(450)

finding positional mean and max

(useful for softmax activation function)

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(0)

In [ ]:
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(90)

Reshaping, stacking , squeezing and unsqueezing tensors

1.Reshaping-reshapes an inout tensor to a defined shape

2.view-return a view of an input tensor of certain shape but keep the same memory as the original tensor

3.stcaking-combine multiple tensor on top of each other(v stack) or side by side(hstack)

4.squeeze- removes all one dimensions from a tensor

5.unsqueeze- adds one dimensions to a target dimnesion

6.permute-return a view of input with dimensions permuted(swapped) in a certain way

In [ ]:
x=torch.arange(1,10)
print(x,x.shape)
#add an extra dimension (reshape)
x_reshaped=x.reshape(3,3)        #total no of elements should be same
x_reshaped,x_reshaped.shape

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]) torch.Size([9])


(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))

In [ ]:
#change the view
#view is similar to reshape but view  shares the memory with original tensor
#chaning z changes x , as both share the same memory
z=x_reshaped.view(1,9)
z,z.shape
#changing z
z[:,0]= 5      #select all rows and first column from 2d array z
z,x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [ ]:
#stack tensors on top of each other
x_stacked=torch.stack([x,x,x,x],dim=0)  #takes list of stacks
x_stacked1=torch.stack([x,x,x,x],dim=1)
print(x_stacked)
x_stacked1

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9]])


tensor([[5, 5, 5, 5],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [ ]:
#squeeze
x=torch.rand(1,1,9)
print(f"original tensor is: {x} and its size is {x.shape }")
x_squeezed=x.squeeze()
print(f"after squeezing the tensor is {x_squeezed}")
x.squeeze().shape


original tensor is: tensor([[[0.6070, 0.7535, 0.0309, 0.5363, 0.5207, 0.8689, 0.5187, 0.5566,
          0.3965]]]) and its size is torch.Size([1, 1, 9])
after squeezing the tensor is tensor([0.6070, 0.7535, 0.0309, 0.5363, 0.5207, 0.8689, 0.5187, 0.5566, 0.3965])


torch.Size([9])

In [ ]:
#unsqueeze
x_unsqueezed=x_squeezed.unsqueeze(dim=0)
print(x_unsqueezed)
x_unsqueezed.shape
x_unsqueezed1=x_unsqueezed.unsqueeze(dim=0)
print(x_unsqueezed1)
x_unsqueezed1.shape


tensor([[0.6070, 0.7535, 0.0309, 0.5363, 0.5207, 0.8689, 0.5187, 0.5566, 0.3965]])
tensor([[[0.6070, 0.7535, 0.0309, 0.5363, 0.5207, 0.8689, 0.5187, 0.5566,
          0.3965]]])


torch.Size([1, 1, 9])

In [ ]:
#permute- permute is a type of view,hence shares same memory
#rearranges dimension of traget tensor in specified order,commonly used while dealing with images
x_original=torch.rand(size=(224,224,3))  #height,width,color channel
x_permuted=x_original.permute(2,0,1)     #width,height,colour channel
print(x_original.shape)
print(x_permuted.shape)

torch.Size([224, 224, 3])
torch.Size([3, 224, 224])


indexing(selecting data from tensors)
similar to indeximg in numpy

In [ ]:
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0]

tensor([1, 2, 3])

In [ ]:
x[0][1][1]

tensor(5)

In [ ]:
x[1,1,1]

In [ ]:
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
x[:,1,1]

tensor([5])

pytorch tensors and numpy

numpy is a popular scientific python numerical computing libarary.

and because of this,pytorch has functionality to interact with it

1.Data in numpy, want in pytorch tensor-> torch.from_numpy(ndarray)

2.pytorch tensor to numpy -> torch.Tensor.numpy()


In [ ]:
#numpy array to tensors
#warning: when converting from numpyto pytorch,pytorch reflects numpy's default datatype
import numpy as np
import torch
array=np.arange(1.0,8.0)      #numpy default dataype is float 64
tensor=torch.from_numpy(array).type(torch.float32)
print(array,tensor)
print(tensor.dtype)
print(array.dtype)

[1. 2. 3. 4. 5. 6. 7.] tensor([1., 2., 3., 4., 5., 6., 7.])
torch.float32
float64


In [ ]:
#change the value in array, what will this do the 'tensor'?
#tensor value does not cahnge
array=array+1
print(array,tensor)


[2. 3. 4. 5. 6. 7. 8.] tensor([1., 2., 3., 4., 5., 6., 7.])


In [ ]:
#Tensor to Numpy array
#numpy araay will be float32(default datatype of tensor)
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
print(tensor,numpy_tensor)
numpy_tensor.dtype

tensor([1., 1., 1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1. 1. 1.]


dtype('float32')

In [ ]:
#change the tensor, what will happen to numpy_tensor?
#no changes
tensor=tensor+1
tensor,numpy_tensor

(tensor([3., 3., 3., 3., 3., 3., 3.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

pytorch reproducibility

taking the random out of random


how a nueral network numbers->tensor operations->update random numbers to try and make them better representations of the data->repeat


to reduce randomness in neural network and pytorch comes the concept of random seed.

essentially what the random seed does is "falvour" the randomness

In [ ]:
import torch
random_tensor_A=torch.rand(3,4)
random_tensor_B=torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)

tensor([[0.7307, 0.3407, 0.2459, 0.8436],
        [0.8122, 0.8910, 0.0536, 0.0030],
        [0.3934, 0.6593, 0.0255, 0.7638]])
tensor([[0.5506, 0.7355, 0.3576, 0.1603],
        [0.2559, 0.4053, 0.2955, 0.8521],
        [0.2132, 0.4954, 0.2947, 0.1470]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
#set the random seed
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)
random_tensor_c=torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_d=torch.rand(3,4)

print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c==random_tensor_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


running tensor and pytorch objects on GPUs(and making faster computation)

GPU=faster computation on numbers(CUDA+NVDIA hardware +pytorch working behind scenes)

**getting a GPU**
1. easiest-use google colab
2.use your own GPU(investment and little setup)
3. use cloud computing-GCP,AWS,Azure, these services allow you you to rent computers on the cloud and access them



In [ ]:
!nvidia-smi


Sun Jun 15 15:54:22 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   48C    P8             12W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
#check for GPU access with pytorch
import torch
torch.cuda.is_available()

True

In [ ]:
#setup device agnostic code
device="cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
#count number of gpus
torch.cuda.device_count()

1

for pytorch since its capable of running compute on the GPU or CPU. its best practice to setup device agnostic code.
eg. run on gpu if available ,else default cpu

setting up device agnostic code and putting tensors on and off the GPU

In [ ]:
#putting tensors(and models) on GPU
import torch
tensor=torch.tensor([1,2,3])
print(tensor,tensor.device)   #tensor by default is in CPU

#move tensor to GPU or target device  if available(setting up device variable)
device="cuda" if torch.cuda.is_available() else "cpu"
tensor_on_gpu=tensor.to(device)
tensor_on_gpu


tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

since numpy only works on cpu
sometimes you need to move back tensors from gpu to cpu

In [ ]:
#if tensor is on gpu, can't transform it to numpy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
#to fix the GPU tensor with Numpy issue,we can first set it to CPU

tensor_back_on_cpu=tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu


array([1, 2, 3])

In [ ]:
tensor_on_gpu   #tensor on gpu is still there unchanged

tensor([1, 2, 3], device='cuda:0')

**exercises**

In [ ]:
#Create a random tensor with shape (7, 7)
tensor=torch.rand(7,7)
tensor

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

In [ ]:
#Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7)

tensor_2=torch.rand(1,7)
tensor_2
torch.matmul(tensor,tensor_2.T)

tensor([[1.7854],
        [1.5805],
        [0.8636],
        [1.1080],
        [0.9550],
        [1.4499],
        [1.4836]])

In [ ]:
#Set the random seed to 0 and do exercises 2 & 3 over again
RANDOM_SEED=0
torch.manual_seed(RANDOM_SEED)
tensor=torch.rand(7,7)
tensor

torch.manual_seed(RANDOM_SEED)
tensor_2=torch.rand(1,7)
tensor_2
torch.matmul(tensor,tensor_2.T)


tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

In [ ]:
#Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.

#torch.manual_seed() — set seed in both cpu and gpu.
#torch.cuda.manual_seed() — set seed to active GPU.
#torch.cuda.manual_seed_all() — set seed to all GPUs.
#For full reproducibility: cudnn.deterministic = True and benchmark = False.

RANDOM_SEED=1234
torch.cuda.manual_seed(RANDOM_SEED)
tensor=torch.rand(1,5,device="cuda")     #if device not mentioned then since rand defaultly create tensors on cpu, fails to give same random numbers each time
tensor


tensor([[0.1272, 0.8167, 0.5440, 0.6601, 0.2721]], device='cuda:0')

In [ ]:
#Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed)

RANDOM_SEED=1234
torch.manual_seed(RANDOM_SEED)
tensor_A=torch.rand(2,3)

torch.manual_seed(RANDOM_SEED)
tensor_B=torch.rand(2,3)
print(tensor_A)
print(tensor_B)

device="cuda" if torch.cuda.is_available() else "cpu"
tensor_A_on_GPU=tensor_A.to(device)
tensor_B_on_GPU=tensor_B.to(device)
print(tensor_A_on_GPU)
print(tensor_B_on_GPU)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')


In [ ]:
#Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).
# Ops run on input tensor's device. Ensure all tensors use same device.
# For large models, use a device variable to move everything safely.

tensor=torch.matmul(tensor_A_on_GPU,tensor_B_on_GPU.T)
tensor

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]], device='cuda:0')

In [ ]:
#Find the maximum and minimum values of the output of 7.
max_value=torch.max(tensor)
min_value=torch.min(tensor)

print(max_value,min_value)

tensor(0.6287, device='cuda:0') tensor(0.2161, device='cuda:0')


In [ ]:
#Find the maximum and minimum index values of the output of 7.
max_value_index=torch.argmax(tensor)
min_value_index=torch.argmin(tensor)
print(max_value_index,min_value_index)

tensor(3, device='cuda:0') tensor(1, device='cuda:0')


In [ ]:
#Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape

RANDOM_SEED=7
tensor_original=torch.rand(1,1,1,10)
print(tensor_original,tensor_original.shape,tensor_original.device)
tensor_squeezed=tensor_original.squeeze()            #torch.squeeze(tensor_original)
print(tensor_squeezed,tensor_squeezed.shape,tensor_squeezed.device)

tensor([[[[0.8436, 0.4265, 0.9561, 0.0770, 0.4108, 0.0014, 0.5414, 0.6419,
           0.2976, 0.7077]]]]) torch.Size([1, 1, 1, 10]) cpu
tensor([0.8436, 0.4265, 0.9561, 0.0770, 0.4108, 0.0014, 0.5414, 0.6419, 0.2976,
        0.7077]) torch.Size([10]) cpu
